### ISSUE TITLE
Buscador de imagens da receita

### ISSUE THREAD

**Issue by eliascoelho911** [eliascoelho911/receitas-api#2]
# Escopo
- As fotos da receita devem ser recuperadas no Google Imagens, e também devem seguir os seguintes filtros:
  - Tamanho grande
  - Formato JPEG ou PNG
___
# Tasks
- [ ] Ler a documentação da API Google Images e descobrir como faço para buscar as imagens, inserindo filtros
- [ ] Utilizar Retrofit para buscar as imagens
- [ ] Devo filtrar apenas:
  - [ ] Imagens relacionadas com a receita
  - [ ] Imagens grandes
  - [ ] Imagens com o formato PNG ou JPEG
